#!/bin/sh
error="🔴"
passed="🟢"
z40=0000000000000000000000000000000000000000
echo "Executing ktlintCheck..."
./gradlew ktlintCheck
if [ $? == 1 ]; then
  echo "$error ktlint failed. Run ktlintFormat then try again."
  exit 1
else
  echo "$passed ktlint passed!"
fi
echo "Executing detekt..."
./gradlew detekt
if [ $? == 1 ]; then
  echo "$error detekt failed. Run detekt then try again."
  exit 1
else
  echo "$passed detekt passed!"
fi
